geoserver/docker

Dockerfile
This updates to the latest tomcat9 version, as 9.0.64 has been removed.
=> Update tomcat version to 9.0.65

Dockerfile, README.md, additional_fonts/.gitignore, additional_libs/.gitignore, docker-compose-demo.yml, geoserver_data/.gitignore, install-extensions.sh, startup.sh
In writing docs and updating readme I found a few things to fix:
=> Troubleshoot Dockerfile handling of data directory and extensions

Dockerfile, README.md, startup.sh
- This PR makes it possible to create an empty GeoServer without demo data, it can be controlled via `SKIP_DEMO_DATA=true`
- The motivation is have a clean GeoServer in production scenarios
- the current behavior of the image stays the same i.e. a new created GeoServer will be populated with demo data
- The change of the PR tries to build around the current usage of the environment variable [`GEOSERVER_REQUIRE_FILE`](https://docs.geoserver.org/stable/en/user/datadirectory/setting.html#require-files-to-exist). This variable is also checked by GeoServer itself and is used to check if demo data should be created. 
Test setup: 
```shell
docker build -t gs-dev . 
docker run \
-p 8080:8080 \
-e SKIP_DEMO_DATA=true \
gs-dev
```
=> Skip demo data on startup

startup.sh
Currently the additional fonts installation fails as they are wrongly counted in the startup.sh script.
=> Making sure additional fonts are correctly counted

BUILD.md, Dockerfile, README.md, RELEASE.md, build/release.sh, install-extensions.sh
This pull-request provides support for nightly builds allowing the testing of community modules:
Here is a working example for building main branch as 2.24.x build:
```
docker build \
--build-arg WAR_ZIP_URL=https://build.geoserver.org/geoserver/main/geoserver-main-latest-war.zip \
--build-arg STABLE_PLUGIN_URL=https://build.geoserver.org/geoserver/main/ext-latest/ \
--build-arg COMMUNITY_PLUGIN_URL=https://build.geoserver.org/geoserver/main/community-latest/ \
--build-arg GS_VERSION=2.24-SNAPSHOT \
-t 2.24.x .
```
When running both [stable extensions](https://build.geoserver.org/geoserver/main/ext-latest/) and [community modules](https://build.geoserver.org/geoserver/main/community-latest/) can be included:
```
docker run -it -p 80:8080 \
--env INSTALL_EXTENSIONS=true \
--env …
```
=> Support for nightly builds

BUILD.md, Dockerfile, README.md, RELEASE.md, build/release.sh
Docker is caching the download step and is not noticing when new war is available for download. This leads to the **geoserver.war** being out of sync with the extensions and community modules installed.
The Dockerfile has three stages:
- tomcat
- download
- install
For a nightly build run with ``--no-cache-filter '!tomcat'`` to avoid caching download and install stages.
=> [GEOS-11016] Use multi-stage build to avoid caching snapshot download

Dockerfile, startup.sh
Hi community,
I'd like to propose this enhancement.
Expected behaviour:
Graceful tomcat shutdown when the container should stop, without delay .
Current behaviour:
The tomcat is killed instead of being shut down, after a delay.
Reason: 
The java process is not process 1 within the container, because of an intermediate shell:
```
F S UID          PID    PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S root           1       0  0  80   0 -   722 do_wai 17:02 ?        00:00:00 /bin/sh -c /opt/startup.sh
0 S root           2       1 94  80   0 - 926044 futex_ 17:02 ?       00:00:25 /usr/bin/java -Djava.util.logging.config.file=/opt/apache-tomcat-9.0.68/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogMan
```
Consequence: The SIGTERM signal issued …
=> Graceful tomcat shutdown

Dockerfile
Hi, 
as of https://github.com/bourgesl/marlin-renderer/releases isn't it better to use 
`-Dsun.java2d.renderer=sun.java2d.marlin.DMarlinRenderingEngine` with openjdk11 ?
ref: https://www.geocat.net/docs/geoserver-enterprise/2020.5/install/production/marlin.html#check-rendering-engine
Java | Rendering Engine | Recommendation
-- | -- | --
Java 8 | sun.dc.DuctusRenderingEngine | This is the Java 8 default rendering engine, recommend installing Marlin.
Java 8 | org.marlin.pisces.MarlinRenderingEngine | Correctly configured with Marlin Rendering Engine
Java 11 | sun.java2d.marlin.DMarlinRenderingEngine | Java 11 defaults to MarlinRenderingEngine
=> org.marlin.pisces to sun.java2d.marlin 

build/release.sh
As per email: `[Geoserver-users] GeoServer 2.24-RC released. Please help us test it`, Andrea says:
```
If I remember correctly, we have had some issue with the docker release script
not handling RC correctly? Like, it's not doing the right thing when it sees "2.24-RC" in the version
and ended up tagging it as part of 2.24.x instead (which I assume has been overwritten by a proper
nightly build by now).
```
This PR adds support for the `-RC` branches.
The publish mode has not been tested due to lack of geoserver-docker.osgeo.org credentials
=> Handle Release Candidate branches

Dockerfile
See https://docs.docker.com/engine/reference/builder/#expose
Otherwise Docker Desktop (Windows) does not know that any ports are exposed:
=> Implement EXPOSE port

Dockerfile
Due to the use of the multistage build feature, we have multiple declarations of `GS_VERSION` in the Dockerfile. For some reason, this value diverged during the latest releases. This MR just fixes the value, but we should investigate the source of the problem and fix it in a follow up.
=> fix: Use consistent version number in Dockerfile

Dockerfile, README.md, config/context.xml, docker-compose-demo.yml, startup.sh
This pull request adds support for creating a PostgreSQL JNDI resource in Apache Tomcat. 
- Included a blurb on the README.md on how to use.
- Provides a default "context.xml" that a user can easily configure using environment variables.
- Provides a mechanism for the user to override the default "context.xml" with their own version of the file for more advanced customization of the connection pool.
Heavily inspired by the work done at https://github.com/kartoza/docker-geoserver.
=> Added support for a PostgreSQL JNDI resource.

README.md
Adding all the env vars in table format in README. The list was obtained using `docker inspect IMAGE_NAME`. 
Some of the values are duplicated with some examples above. 
Some points that can be further added are:
- Reference to docs for JAVA variables 
- Reference to dosc for CATALINA variables 
- Some variables should not be changed like `GEOSERVER_VERSION` so maybe mark them as `should not change`? (confused on this) 
- Add sample value for empty places
=> Docs: Add docker ENV vars in README

Dockerfile, README.md, docker-compose-demo.yml
This PR introduces a configurable docker health check (see also here).
Currently, the logo of the landing page is used for check, however it can be configured using the HEALTHCHECK_URL environment variable.
In the demo docker compose file a corresponding block for the postgis database has been added.
=> Introduce health checks for GeoServer (and postgis db in demo)

.github/workflows/trivy.yml
For the time being it should be fine to have the output of the github action (security scan) as a background info, but it should not be blocking in any way.
=> chore: do not fail with known vulns

.github/workflows/trivy.yml
Herewith the results of the trivy scan are published to GitHub Security tab
Please review.
=> Configure trivy action to upload results to security tab

.github/workflows/trivy.yml
Fixes the output format of `trivy` workflow.
=> fix: use sarif format in trivy results

Dockerfile
The problem described in https://github.com/geoserver/docker/pull/39#issuecomment-1954273220 is a result of the custom `geoserver` user that runs the tomcat in the docker container (see changset of this PR). This user is currently not allowed to create the additional libs dir, which is required for their installation.
We also found out that this custom user may lead to problems in setups with docker mounts, which could be solved by changing file/directory ownerships on the host system to `2000:2000` (which is/was the geoserver uid in the container).
To be able to include the recent changes in this project for the current/next geoserver release, we propose to revert the introduction of the custom `geoserver` user for the time being.
**Note: Herewith, the user running the tomcat process …
=> fix: do not run as custom user

Dockerfile
GeoServer won't start if you have e.g. a style with an umlaut in the filename. With this PR this is fixed.
=> fix: allow unicode filenames

.dockerignore, .gitignore
Ignore a potential postgis subdir that may be created when using the docker compose example. Without this change, you could end up with permission problems when using docker for the project.
=> feat: ignore pg data when using compose example

Dockerfile, startup.sh, update_credentials.sh
This project lacked the option of specifying the username and password of the admin user via environment variables. With this PR it's possible to set the admin credentials like so:
```sh
podman run -d -p 8081:8080 -e GEOSERVER_ADMIN_USER=admin -e GEOSERVER_ADMIN_PASSWORD=geoserver <image>
```
The changes are heavily influenced by preliminary work of [meggsimum](https://github.com/meggsimum/geoserver-docker/) and [kartoza](https://github.com/kartoza/docker-geoserver).
=> Set admin credentials with environment variables

update_credentials.sh
As `//` inside of a path will be ignored in the shell, it might be safer to use more slashes.
Don't know if this is desired, it makes the whole thing a little more robust imho.
We had a problem where the security directory was copied over everytime and the masterpasswd changed on every restart.
=> fix: use more slashes to make script more robust

Dockerfile
OpenJDK Java 11 reaches end-of-life October 2024. So this updates from JDK11 to JDK17.
According to https://github.com/geoserver/geoserver/wiki/Release-Schedule#2024 GeoServer 2.26.0 will be the first version supporting this "officially"
@jodygarnett maybe it makes sense to merge this before building 2.26.0 ?
=> chore: use JDK 17

Dockerfile, startup.sh
It is a good practice to allow running a container as unprivileged user. 
To preserve backward compatibility and provide flexibility, this feature is added at the entrypoint level and is set using environment variables.
- RUN_UNPRIVILEGED=true activates the unprivileged mode with default uid:gid as 999:999
- RUN_WITH_USER_UID allows to set the uid used for tomcat user
- RUN_WITH_USER_UID allows to set the gid used for tomcat group
- CHANGE_OWNERSHIP_ON_FOLDERS accepts a space-separated list of folder on which a chmod will be run, changing (recursively) the ownership for the tomcat user.
=> Allow running tomcat as non-root

README.md
There is a bug after the restart of the docker container. If the env variable `GEOSERVER_ADMIN_USER` and `GEOSERVER_ADMIN_PASSWORD` are set, new added users and roles are overwritten after a restart. You can avoid this, if you unset the vars after the first run.
I don't know if this is intentional, but perhaps it could be fixed on the code side?
=> update readme with information about credential overwrite issue

README.md
Commit https://github.com/geoserver/docker/commit/ce561ff777f64756e4f0ed4692e2782005b0e11b removed `context.xml` and moved it into `server.xml`.
Previously, I used `context.xml` to configure JNDI for my geoservers, taking advantage of some local conventions to limit the amount of environment variables.
After updating from 2.25.x to 2.26.1 today, it took me some time to discover why my JNDI wasn't being found anymore :-) Cause: my `context.xml` wasn't used anymore.
So I've documented it.
=> Documented that context.xml isn't used anymore

Dockerfile, README.md, build/release.sh
This pull request allows the integration of **GDAL** into the resulting GeoServer docker image. With a specific focus on **building the Java bindings**. Unlike the default Ubuntu package sources (like `gdal-bin`), which do not only provide an outdated version, but especially do not provide the Java bindings, this implementation ensures full compatibility with GDAL.
Related links:
* https://osgeo-org.atlassian.net/browse/GEOS-11684
* https://github.com/geoserver/docker/pull/135
* https://trac.osgeo.org/osgeolive/ticket/2288
* https://gdal.org/en/stable/api/java/index.html
* https://github.com/OSGeo/gdal/tree/master/docker/ubuntu-small (credits go here for the gdal build stage)
Usage: `docker build --build-arg BUILD_GDAL=true -t my-geoserver-image .`
Note: On average hardware, this takes …
=> Add GDAL with Java Bindings Support

Dockerfile
It seems that buildkit is currently not activated/available in the build environment, but we can easily disable these cache mounts
=> fix: do not use docker buildkit features
